# Copyright: 2008-2010 RobotCub Consortium
# Author: Stéphane Lallée
# CopyPolicy: Released under the terms of the GNU GPL v2.0.
SET(FFTW3_ROOT_DIR "$ENV{FFTW3_DIR}")
SET(FFTW3_INCLUDE_DIR "${FFTW3_ROOT_DIR}")
SET(FFTW3_LIB_DIR "${FFTW3_ROOT_DIR}")
SET(FFTW3_LIBRARIES 
	"${FFTW3_ROOT_DIR}/libfftw3-3.lib"
	"${FFTW3_ROOT_DIR}/libfftw3f-3.lib"
	"${FFTW3_ROOT_DIR}/libfftw3l-3.lib"
)
SET(FFTW3_INCLUDES 
	"${FFTW3_INCLUDE_DIR}/fftw3.h"
)

####################   Macro   #######################
MACRO(CHECK_FILES _FILES _DIR)
	SET(_MISSING_FILES)
	FOREACH(_FILE ${${_FILES}})
		IF(NOT EXISTS "${_FILE}")
			SET(FFTW3_FOUND NO)
			get_filename_component(_FILE ${_FILE} NAME)
			SET(_MISSING_FILES "${_MISSING_FILES}${_FILE}, ")
		ENDIF()
	ENDFOREACH()
	IF(_MISSING_FILES)
		MESSAGE(STATUS "In folder \"${${_DIR}}\" not found files: ${_MISSING_FILES}")
		SET(FFTW3_FOUND NO)
	ENDIF()
ENDMACRO(CHECK_FILES)

MACRO(CHECK_DIR _DIR)
	IF(NOT EXISTS "${${_DIR}}")
		#MESSAGE(STATUS "Folder \"${${_DIR}}\" not found.")
		SET(FFTW3_FOUND NO)
	ENDIF()
ENDMACRO(CHECK_DIR)

##################### Checking #######################
MESSAGE(STATUS "Searching FFT3W.")
SET(FFTW3_FOUND TRUE)

CHECK_DIR(FFTW3_ROOT_DIR)
IF(FFTW3_FOUND)
	CHECK_DIR(FFTW3_INCLUDE_DIR)
	
	IF(FFTW3_FOUND)
		CHECK_FILES(FFTW3_LIBRARIES FFTW3_LIB_DIR)
		CHECK_FILES(FFTW3_INCLUDES FFTW3_INCLUDE_DIR)
	ENDIF()
ENDIF()

MESSAGE(STATUS "FFTW3_FOUND - ${FFTW3_FOUND}.")