function img_output = genMatchSynth(KineStruct_P, KineStruct_Q, X)

height_normalised = 240;
width_normalised = 800;

% height_normalised = 480;
% width_normalised = 640;

ratio_height_P = 1;
ratio_width_P = 1;
ratio_height_Q = 1;
ratio_width_Q = 1;

%%
% draw image
figure(1011)
clf
iptsetpref('ImshowBorder','tight')

% Drawing the connections with color segments
color_idx = 'rgbcmy';
% marker_idx = '+o*xsd^v><ph';
marker_idx = '............';

% for Graph P
frm_idx_P = KineStruct_P.num_frames;

% for Graph Q
frm_idx_Q = KineStruct_Q.num_frames-10;

% drawing connections for Graph P
for m = 1:size(KineStruct_P.structure_i,1)
    hold on
    %     plot([KineStruct_P.seg_center(1,KineStruct_P.structure_i(m),frm_idx_P) * ratio_width_P, KineStruct_P.seg_center(1,KineStruct_P.structure_j(m),frm_idx_P) * ratio_width_P],...
    %         [KineStruct_P.seg_center(2,KineStruct_P.structure_i(m),frm_idx_P) * ratio_height_P, KineStruct_P.seg_center(2,KineStruct_P.structure_j(m),frm_idx_P) * ratio_height_P],'-wo',...
    %         'LineWidth',4,...
    %         'MarkerSize',15,...
    %         'MarkerEdgeColor','w',...
    %         'MarkerFaceColor',[1.0,0.2,0.2]);
    
    joint_pts_buf = KineStruct_P.joint_center{KineStruct_P.structure_i(m),KineStruct_P.structure_j(m)};

    % Connection
    plot([KineStruct_P.seg_center(1,KineStruct_P.structure_i(m),frm_idx_P) * ratio_width_P, joint_pts_buf(1,frm_idx_P) * ratio_width_P],[KineStruct_P.seg_center(2,KineStruct_P.structure_i(m),frm_idx_P) * ratio_height_P, joint_pts_buf(2,frm_idx_P) * ratio_height_P],'-k','LineWidth',4);
    plot([KineStruct_P.seg_center(1,KineStruct_P.structure_j(m),frm_idx_P) * ratio_width_P, joint_pts_buf(1,frm_idx_P) * ratio_width_P],[KineStruct_P.seg_center(2,KineStruct_P.structure_j(m),frm_idx_P) * ratio_height_P, joint_pts_buf(2,frm_idx_P) * ratio_height_P],'-k','LineWidth',4);
    
    % Node
    plot([KineStruct_P.seg_center(1,KineStruct_P.structure_i(m),frm_idx_P) * ratio_width_P],[KineStruct_P.seg_center(2,KineStruct_P.structure_i(m),frm_idx_P) * ratio_height_P],'-ks',...
        'LineWidth',3,...
        'MarkerSize',15,...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor',[1.0,0.2,0.2]);
    plot([KineStruct_P.seg_center(1,KineStruct_P.structure_j(m),frm_idx_P) * ratio_width_P],[KineStruct_P.seg_center(2,KineStruct_P.structure_j(m),frm_idx_P) * ratio_height_P],'-ks',...
        'LineWidth',3,...
        'MarkerSize',15,...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor',[1.0,0.2,0.2]);
    
    % Joint
    plot(joint_pts_buf(1,frm_idx_P) * ratio_width_P, joint_pts_buf(2,frm_idx_P) * ratio_height_P,'ko',...
        'LineWidth',1,...
        'MarkerSize',9,...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor',[1.0,0.647,0.0]);
    plot(joint_pts_buf(1,frm_idx_P) * ratio_width_P, joint_pts_buf(2,frm_idx_P) * ratio_height_P,'kx',...
        'LineWidth',1,...
        'MarkerSize',9,...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor',[1.0,0.647,0.0]);
        
    
end
% drawing connections for Graph Q
for m = 1:size(KineStruct_Q.structure_i,1)
    hold on
    %     plot([width_normalised + KineStruct_Q.seg_center(1,KineStruct_Q.structure_i(m),frm_idx_Q) * ratio_width_Q, width_normalised + KineStruct_Q.seg_center(1,KineStruct_Q.structure_j(m),frm_idx_Q) * ratio_width_Q],...
    %         [KineStruct_Q.seg_center(2,KineStruct_Q.structure_i(m),frm_idx_Q) * ratio_height_Q, KineStruct_Q.seg_center(2,KineStruct_Q.structure_j(m),frm_idx_Q) * ratio_height_Q],'-wo',...
    %         'LineWidth',4,...
    %         'MarkerSize',15,...
    %         'MarkerEdgeColor','w',...
    %         'MarkerFaceColor',[1.0,0.2,0.2]);
    
    joint_pts_buf = KineStruct_Q.joint_center{KineStruct_Q.structure_i(m),KineStruct_Q.structure_j(m)};
  
    % Connection
    plot([width_normalised + KineStruct_Q.seg_center(1,KineStruct_Q.structure_i(m),frm_idx_Q) * ratio_width_Q, width_normalised + joint_pts_buf(1,frm_idx_Q) * ratio_width_Q],[KineStruct_Q.seg_center(2,KineStruct_Q.structure_i(m),frm_idx_Q) * ratio_height_Q, joint_pts_buf(2,frm_idx_Q) * ratio_height_Q],'-k','LineWidth',4);
    plot([width_normalised + KineStruct_Q.seg_center(1,KineStruct_Q.structure_j(m),frm_idx_Q) * ratio_width_Q, width_normalised + joint_pts_buf(1,frm_idx_Q) * ratio_width_Q],[KineStruct_Q.seg_center(2,KineStruct_Q.structure_j(m),frm_idx_Q) * ratio_height_Q, joint_pts_buf(2,frm_idx_Q) * ratio_height_Q],'-k','LineWidth',4);
    
    % Node
    plot([width_normalised + KineStruct_Q.seg_center(1,KineStruct_Q.structure_i(m),frm_idx_Q) * ratio_width_Q],[KineStruct_Q.seg_center(2,KineStruct_Q.structure_i(m),frm_idx_Q) * ratio_height_Q],'-ks',...
        'LineWidth',3,...
        'MarkerSize',15,...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor',[1.0,0.2,0.2]);
    plot([width_normalised + KineStruct_Q.seg_center(1,KineStruct_Q.structure_j(m),frm_idx_Q) * ratio_width_Q],[KineStruct_Q.seg_center(2,KineStruct_Q.structure_j(m),frm_idx_Q) * ratio_height_Q],'-ks',...
        'LineWidth',3,...
        'MarkerSize',15,...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor',[1.0,0.2,0.2]);
    
    % Joint
    plot(width_normalised + joint_pts_buf(1,frm_idx_Q) * ratio_width_Q, joint_pts_buf(2,frm_idx_Q) * ratio_height_Q,'ko',...
        'LineWidth',1,...
        'MarkerSize',9,...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor',[1.0,0.647,0.0]);
    plot(width_normalised + joint_pts_buf(1,frm_idx_Q) * ratio_width_Q, joint_pts_buf(2,frm_idx_Q) * ratio_height_Q,'kx',...
        'LineWidth',1,...
        'MarkerSize',9,...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor',[1.0,0.647,0.0]);    
    
end

%% Draw matches
for p = 1:size(X,1)
    for q = 1:size(X,2)
        if X(p,q) > 0
            hold on
            plot([KineStruct_P.seg_center(1,p,frm_idx_P) * ratio_width_P, width_normalised + KineStruct_Q.seg_center(1,q,frm_idx_Q) * ratio_width_Q],...
                [KineStruct_P.seg_center(2,p,frm_idx_P) * ratio_height_P, KineStruct_Q.seg_center(2,q,frm_idx_Q) * ratio_height_Q],'-k.',...
                'LineWidth',4,...
                'MarkerSize',10,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor',[1.0,0.2,0.2]);
            plot([KineStruct_P.seg_center(1,p,frm_idx_P) * ratio_width_P, width_normalised + KineStruct_Q.seg_center(1,q,frm_idx_Q) * ratio_width_Q],...
                [KineStruct_P.seg_center(2,p,frm_idx_P) * ratio_height_P, KineStruct_Q.seg_center(2,q,frm_idx_Q) * ratio_height_Q],'-y.',...
                'LineWidth',2,...
                'MarkerSize',10,...
                'MarkerEdgeColor','y',...
                'MarkerFaceColor',[1.0,0.2,0.2]);
        end
    end
end

img_output = getimage;

end